[2025-01-14T05:02:52.136+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T05:02:51.477462+00:00 [queued]>
[2025-01-14T05:02:52.142+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T05:02:51.477462+00:00 [queued]>
[2025-01-14T05:02:52.142+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-01-14T05:02:52.142+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 2
[2025-01-14T05:02:52.142+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-01-14T05:02:52.148+0000] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): data_extract> on 2025-01-14 05:02:51.477462+00:00
[2025-01-14T05:02:52.152+0000] {standard_task_runner.py:52} INFO - Started process 807 to run task
[2025-01-14T05:02:52.155+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ETL_influencer_marchendise', 'data_extract', 'manual__2025-01-14T05:02:51.477462+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/AirflowM3.py', '--cfg-path', '/tmp/tmpgicslnwk', '--error-file', '/tmp/tmpr_4exm22']
[2025-01-14T05:02:52.156+0000] {standard_task_runner.py:80} INFO - Job 3: Subtask data_extract
[2025-01-14T05:02:52.224+0000] {task_command.py:371} INFO - Running <TaskInstance: ETL_influencer_marchendise.data_extract manual__2025-01-14T05:02:51.477462+00:00 [running]> on host f0721e5f96e7
[2025-01-14T05:02:52.266+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=afif
AIRFLOW_CTX_DAG_ID=ETL_influencer_marchendise
AIRFLOW_CTX_TASK_ID=data_extract
AIRFLOW_CTX_EXECUTION_DATE=2025-01-14T05:02:51.477462+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-14T05:02:51.477462+00:00
[2025-01-14T05:02:52.266+0000] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-14T05:02:52.267+0000] {subprocess.py:74} INFO - Running command: ['/bin/bash', '-c', 'sudo -u *** python /opt/***/dags/extract.py']
[2025-01-14T05:02:52.272+0000] {subprocess.py:85} INFO - Output:
[2025-01-14T05:02:52.430+0000] {subprocess.py:92} INFO - Traceback (most recent call last):
[2025-01-14T05:02:52.430+0000] {subprocess.py:92} INFO -   File "/opt/***/dags/extract.py", line 44, in <module>
[2025-01-14T05:02:52.430+0000] {subprocess.py:92} INFO -     extract(path)
[2025-01-14T05:02:52.430+0000] {subprocess.py:92} INFO - TypeError: extract() missing 1 required positional argument: 'st_path'
[2025-01-14T05:02:52.443+0000] {subprocess.py:96} INFO - Command exited with return code 1
[2025-01-14T05:02:52.451+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-14T05:02:52.453+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_influencer_marchendise, task_id=data_extract, execution_date=20250114T050251, start_date=20250114T050252, end_date=20250114T050252
[2025-01-14T05:02:52.459+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task data_extract (Bash command failed. The command returned a non-zero exit code 1.; 807)
[2025-01-14T05:02:52.465+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-01-14T05:02:52.482+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
